name: Build and Push Container

on:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: cloudguardian

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::788607671185:role/CloudGuardian-GitHubActions-ECR
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest

      - name: Deploy to EC2 via SSM
        run: |
          aws ssm send-command \
            --instance-ids i-009acc22e9ffbc1f6 \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=["/home/ubuntu/cloudguardian/deploy.sh"]' \
            --region ${{ env.AWS_REGION }}
